services:
  redis:
    image: redis:latest
    restart: unless-stopped
    container_name: "redis"
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/var/lib/redis
    command: redis-server --requirepass ${REDIS_DEFAULT_PASS}  # --notify-keyspace-events Ex
    env_file:
      - .env
  postgres:
    image: postgres:latest
    ports:
      - "${DEFAULT_DB_PORT}:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DEFAULT_DB_PASSWORD}
      - POSTGRES_USER=${DEFAULT_DB_USER}
      - POSTGRES_DB=${DEFAULT_DB_NAME}
    env_file:
      - .env
