"""init db

Revision ID: 6bb76b72a3fd
Revises: 
Create Date: 2022-11-23 09:24:29.694865

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6bb76b72a3fd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_group',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('auth_permission',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('auth_role',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('auth_user',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('circuit_provider',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asn', sa.String(), nullable=True),
    sa.Column('account', sa.String(), nullable=True),
    sa.Column('portal', sa.String(), nullable=True),
    sa.Column('noc_contact', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('admin_contact', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('comments', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('circuit_type',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cluster',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('dcim_cable',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cable_type', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dcim_device_role',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vm_role', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dcim_manufacturer',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dcim_platform',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('napalm_driver', sa.String(), nullable=True),
    sa.Column('napalm_args', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dcim_rack_role',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dcim_region',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['dcim_region.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dcim_site_group',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_code', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_code')
    )
    op.create_table('dcim_virtual_chassis',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ipam_asn',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asn', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asn')
    )
    op.create_table('ipam_rir',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_private', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ipam_role',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ipam_vlan_group',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tenant',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('auth_group_role_link',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['auth_group.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['auth_role.id'], ),
    sa.PrimaryKeyConstraint('group_id', 'role_id')
    )
    op.create_table('auth_role_permission_link',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['auth_permission.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['auth_role.id'], ),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('auth_user_group_link',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['auth_group.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'group_id')
    )
    op.create_table('auth_user_role_link',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['auth_role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('circuit',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cid', sa.String(), nullable=True),
    sa.Column('provider_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('circuit_type_id', sa.Integer(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('install_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('purchase_term', sa.String(), nullable=True),
    sa.Column('commit_rate', sa.Integer(), nullable=True, comment='Mbps'),
    sa.Column('comments', sa.TEXT(), nullable=True),
    sa.Column('vendor_available_ip', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('vendor_available_gateway', postgresql.ARRAY(sa.String()), nullable=True),
    sa.ForeignKeyConstraint(['circuit_type_id'], ['circuit_type.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['provider_id'], ['circuit_provider.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cid')
    )
    op.create_table('dcim_cable_termination',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cable_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cable_id'], ['dcim_cable.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dcim_device_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('manufacturer_id', sa.Integer(), nullable=True),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('u_height', sa.Float(), server_default='1.0', nullable=True),
    sa.Column('is_full_depth', sa.Boolean(), server_default=sa.text('true'), nullable=True),
    sa.ForeignKeyConstraint(['manufacturer_id'], ['dcim_manufacturer.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('manufacturer_id', 'model')
    )
    op.create_table('dcim_site',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_code', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('facility', sa.String(), nullable=True),
    sa.Column('time_zone', sa.String(), nullable=True),
    sa.Column('physical_address', sa.String(), nullable=True),
    sa.Column('shipping_address', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['dcim_site_group.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['region_id'], ['dcim_region.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site_code')
    )
    op.create_table('ipam_block',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prefix', postgresql.CIDR(), nullable=False),
    sa.Column('rir_id', sa.Integer(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['rir_id'], ['ipam_rir.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ipam_route_target',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ipam_vrf',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rd', sa.String(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('enforce_unique', sa.Boolean(), server_default=sa.text('true'), nullable=True, comment='Enforce unique space, prevent duplicate IP/prefix'),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rd')
    )
    op.create_table('server',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('platform_id', sa.Integer(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('primary_ipv4', postgresql.INET(), nullable=True),
    sa.Column('primary_ipv6', postgresql.INET(), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String(), dimensions=1), nullable=True),
    sa.Column('cluster_id', sa.Integer(), nullable=True),
    sa.Column('is_vm', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('cpu', sa.Integer(), nullable=True),
    sa.Column('memory', sa.String(), nullable=False),
    sa.Column('disk', sa.String(), nullable=True),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cluster_id'], ['cluster.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['contact_id'], ['contact.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['platform_id'], ['dcim_platform.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['role_id'], ['dcim_device_role.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tenant_contact_link',
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contact.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('tenant_id', 'contact_id')
    )
    op.create_table('tenant_ipam_asn_link',
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('asn_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['asn_id'], ['ipam_asn.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('tenant_id', 'asn_id')
    )
    op.create_table('circuit_termination',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('term_side', sa.String(), nullable=False),
    sa.Column('circuit_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['circuit_id'], ['circuit.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('circuit_id', 'term_side')
    )
    op.create_table('dcim_location',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['dcim_location.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['dcim_site.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dcim_site_contact_link',
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contact.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['dcim_site.id'], ),
    sa.PrimaryKeyConstraint('site_id', 'contact_id')
    )
    op.create_table('ipam_ip_address',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', postgresql.INET(), nullable=False),
    sa.Column('vrf_id', sa.Integer(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('dns_name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vrf_id'], ['ipam_vrf.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ipam_ip_range',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_address', postgresql.INET(), nullable=True),
    sa.Column('end_address', postgresql.INET(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('vrf_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['ipam_role.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vrf_id'], ['ipam_vrf.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ipam_prefix',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prefix', postgresql.CIDR(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('is_pool', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['ipam_role.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['site_id'], ['dcim_site.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ipam_vlan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('vlan_group_id', sa.Integer(), nullable=True),
    sa.Column('vid', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['ipam_role.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['site_id'], ['dcim_site.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vlan_group_id'], ['ipam_vlan_group.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site_id', 'vlan_group_id', 'vid', 'id')
    )
    op.create_table('ipam_vrf_route_target_link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vrf_id', sa.Integer(), nullable=False),
    sa.Column('route_target_id', sa.Integer(), nullable=False),
    sa.Column('target_type', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['route_target_id'], ['ipam_route_target.id'], ),
    sa.ForeignKeyConstraint(['vrf_id'], ['ipam_vrf.id'], ),
    sa.PrimaryKeyConstraint('id', 'vrf_id', 'route_target_id')
    )
    op.create_table('tenant_asn_link',
    sa.Column('circuit_id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['circuit_id'], ['circuit.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['contact.id'], ),
    sa.PrimaryKeyConstraint('circuit_id', 'contact_id')
    )
    op.create_table('dcim_rack',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('facility_id', sa.String(), nullable=True),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('serial_num', sa.String(), nullable=True),
    sa.Column('asset_tag', sa.String(), nullable=True),
    sa.Column('rack_type', sa.String(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=False, comment='Rail-to-rail width'),
    sa.Column('u_height', sa.Integer(), nullable=False, comment='Height in rack units'),
    sa.Column('desc_units', sa.Boolean(), server_default=sa.text('false'), nullable=True, comment='Units are numbered top-to-bottom'),
    sa.Column('outer_width', sa.Integer(), nullable=False, comment='Outer dimension of rack (width)'),
    sa.Column('outer_depth', sa.Integer(), nullable=False, comment='Outer dimension of rack (depth)'),
    sa.Column('outer_unit', sa.String(), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['dcim_location.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['site_id'], ['dcim_site.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_tag')
    )
    op.create_table('dcim_device',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('primary_ipv4', postgresql.INET(), nullable=True),
    sa.Column('primary_ipv6', postgresql.INET(), nullable=True),
    sa.Column('device_type_id', sa.Integer(), nullable=True),
    sa.Column('device_role_id', sa.Integer(), nullable=True),
    sa.Column('platform_id', sa.Integer(), nullable=True),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('rack_id', sa.Integer(), nullable=True),
    sa.Column('position', sa.Float(), nullable=True),
    sa.Column('serial_num', sa.String(), nullable=True),
    sa.Column('asset_tag', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('cluster_id', sa.Integer(), nullable=True),
    sa.Column('chassis_id', sa.Integer(), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['chassis_id'], ['dcim_virtual_chassis.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['cluster_id'], ['cluster.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['device_role_id'], ['dcim_device_role.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['device_type_id'], ['dcim_device_type.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['location_id'], ['dcim_location.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['platform_id'], ['dcim_platform.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rack_id'], ['dcim_rack.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['site_id'], ['dcim_site.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_tag'),
    sa.UniqueConstraint('chassis_id', 'name'),
    sa.UniqueConstraint('rack_id', 'position')
    )
    op.create_table('dcim_interface',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('if_index', sa.Integer(), nullable=True),
    sa.Column('speed', sa.Integer(), nullable=True),
    sa.Column('mode', postgresql.ENUM('access', 'trunk', 'layer-3', name='mode_enum'), nullable=True),
    sa.Column('mtu', sa.Integer(), nullable=True),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['dcim_device.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dcim_interface')
    op.drop_table('dcim_device')
    op.drop_table('dcim_rack')
    op.drop_table('tenant_asn_link')
    op.drop_table('ipam_vrf_route_target_link')
    op.drop_table('ipam_vlan')
    op.drop_table('ipam_prefix')
    op.drop_table('ipam_ip_range')
    op.drop_table('ipam_ip_address')
    op.drop_table('dcim_site_contact_link')
    op.drop_table('dcim_location')
    op.drop_table('circuit_termination')
    op.drop_table('tenant_ipam_asn_link')
    op.drop_table('tenant_contact_link')
    op.drop_table('server')
    op.drop_table('ipam_vrf')
    op.drop_table('ipam_route_target')
    op.drop_table('ipam_block')
    op.drop_table('dcim_site')
    op.drop_table('dcim_device_type')
    op.drop_table('dcim_cable_termination')
    op.drop_table('circuit')
    op.drop_table('auth_user_role_link')
    op.drop_table('auth_user_group_link')
    op.drop_table('auth_role_permission_link')
    op.drop_table('auth_group_role_link')
    op.drop_table('tenant')
    op.drop_table('ipam_vlan_group')
    op.drop_table('ipam_role')
    op.drop_table('ipam_rir')
    op.drop_table('ipam_asn')
    op.drop_table('dcim_virtual_chassis')
    op.drop_table('dcim_site_group')
    op.drop_table('dcim_region')
    op.drop_table('dcim_rack_role')
    op.drop_table('dcim_platform')
    op.drop_table('dcim_manufacturer')
    op.drop_table('dcim_device_role')
    op.drop_table('dcim_cable')
    op.drop_table('contact')
    op.drop_table('cluster')
    op.drop_table('circuit_type')
    op.drop_table('circuit_provider')
    op.drop_table('auth_user')
    op.drop_table('auth_role')
    op.drop_table('auth_permission')
    op.drop_table('auth_group')
    # ### end Alembic commands ###
