"""init db

Revision ID: aedfbb298f93
Revises:
Create Date: 2024-07-09 21:21:30.777580

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

import src
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "aedfbb298f93"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto;")
    op.execute("CREATE EXTENSION IF NOT EXISTS hstore;")
    op.create_table(
        "alert",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", postgresql.HSTORE(text_type=sa.Text()), nullable=False),
        sa.Column("slug", sa.String(), nullable=False),
        sa.Column("description", postgresql.HSTORE(text_type=sa.Text()), nullable=False),
        sa.Column("possible_impacts", postgresql.HSTORE(text_type=sa.Text()), nullable=False),
        sa.Column("remediation_suggestion", postgresql.HSTORE(text_type=sa.Text()), nullable=False),
        sa.Column("references", sa.String(), nullable=True),
        sa.Column("severity", sa.String(), nullable=False),
        sa.Column("created_at", src.core.database.types.datetime.DateTimeTZ(timezone=True), nullable=False),
        sa.Column("updated_at", src.core.database.types.datetime.DateTimeTZ(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
        sa.UniqueConstraint("slug"),
    )
    op.create_index(op.f("ix_alert_created_at"), "alert", ["created_at"], unique=False)
    op.create_index(op.f("ix_alert_id"), "alert", ["id"], unique=False)
    op.create_table(
        "asn",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("asn", sa.Integer(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("created_at", src.core.database.types.datetime.DateTimeTZ(timezone=True), nullable=False),
        sa.Column("updated_at", src.core.database.types.datetime.DateTimeTZ(timezone=True), nullable=False),
        sa.Column("created_by_fk", sa.Integer(), nullable=True),
        sa.Column("updated_by_fk", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("asn"),
    )
    op.create_index(op.f("ix_asn_created_at"), "asn", ["created_at"], unique=False)
    op.create_index(op.f("ix_asn_id"), "asn", ["id"], unique=False)
    op.create_table(
        "block",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("block", src.core.database.types.ipaddress.PgCIDR(), nullable=False),
        sa.Column("size", sa.Integer(), nullable=False),
        sa.Column("range", sa.String(), nullable=False),
        sa.Column("is_private", sa.Boolean(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("created_at", src.core.database.types.datetime.DateTimeTZ(timezone=True), nullable=False),
        sa.Column("updated_at", src.core.database.types.datetime.DateTimeTZ(timezone=True), nullable=False),
        sa.Column("created_by_fk", sa.Integer(), nullable=True),
        sa.Column("updated_by_fk", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("block"),
    )
    op.create_index(op.f("ix_block_created_at"), "block", ["created_at"], unique=False)
    op.create_index(op.f("ix_block_id"), "block", ["id"], unique=False)
    op.create_table(
        "circuit_type",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", postgresql.HSTORE(text_type=sa.Text()), nullable=False),
        sa.Column("slug", sa.String(), nullable=False),
        sa.Column("connection_type", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("created_at", src.core.database.types.datetime.DateTimeTZ(timezone=True), nullable=False),
        sa.Column("updated_at", src.core.database.types.datetime.DateTimeTZ(timezone=True), nullable=False),
        sa.Column("created_by_fk", sa.Integer(), nullable=True),
        sa.Column("updated_by_fk", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )
    op.create_index(op.f("ix_circuit_type_created_at"), "circuit_type", ["created_at"], unique=False)
    op.create_index(op.f("ix_circuit_type_id"), "circuit_type", ["id"], unique=False)
    op.create_table(
        "correlation",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("source_match", postgresql.JSON(astext_type=sa.Text()), nullable=False),
        sa.Column("target_match", postgresql.JSON(astext_type=sa.Text()), nullable=False),
        sa.Column("equal_value", postgresql.JSON(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", src.core.database.types.datetime.DateTimeTZ(timezone=True), nullable=False),
        sa.Column("updated_at", src.core.database.types.datetime.DateTimeTZ(timezone=True), nullable=False),
        sa.Column("created_by_fk", sa.Integer(), nullable=True),
        sa.Column("updated_by_fk", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_correlation_created_at"), "correlation", ["created_at"], unique=False)
    op.create_index(op.f("ix_correlation_id"), "correlation", ["id"], unique=False)
    op.create_table(
        "device_role",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", postgresql.HSTORE(text_type=sa.Text()), nullable=False),
        sa.Column("slug", sa.String(), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("abbreviation", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("created_at", src.core.database.types.datetime.DateTimeTZ(timezone=True), nullable=False),
        sa.Column("updated_at", src.core.database.types.datetime.DateTimeTZ(timezone=True), nullable=False),
        sa.Column("created_by_fk", sa.Integer(), nullable=True),
        sa.Column("updated_by_fk", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )
    op.create_index(op.f("ix_device_role_created_at"), "device_role", ["created_at"], unique=False)
    op.create_index(op.f("ix_device_role_id"), "device_role", ["id"], unique=False)
    op.create_table(
        "inhibitor",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("started_at", src.core.database.types.datetime.DateTimeTZ(timezone=True), nullable=False),
        sa.Column("ended_at", src.core.database.types.datetime.DateTimeTZ(timezone=True), nullable=False),
        sa.Column("rules", postgresql.JSON(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", src.core.database.types.datetime.DateTimeTZ(timezone=True), nullable=False),
        sa.Column("updated_at", src.core.database.types.datetime.DateTimeTZ(timezone=True), nullable=False),
        sa.Column("created_by_fk", sa.Integer(), nullable=True),
        sa.Column("updated_by_fk", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_inhibitor_created_at"), "inhibitor", ["created_at"], unique=False)
    op.create_index(op.f("ix_inhibitor_id"), "inhibitor", ["id"], unique=False)
    op.create_table(
        "ip_role",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", postgresql.HSTORE(text_type=sa.Text()), nullable=False),
        sa.Column("slug", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("created_at", src.core.database.types.datetime.DateTimeTZ(timezone=True), nullable=False),
        sa.Column("updated_at", src.core.database.types.datetime.DateTimeTZ(timezone=True), nullable=False),
        sa.Column("created_by_fk", sa.Integer(), nullable=True),
        sa.Column("updated_by_fk", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )
    op.create_index(op.f("ix_ip_role_created_at"), "ip_role", ["created_at"], unique=False)
    op.create_index(op.f("ix_ip_role_id"), "ip_role", ["id"], unique=False)
    op.create_table(
        "isp",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", postgresql.HSTORE(text_type=sa.Text()), nullable=False),
        sa.Column("portal", sa.String(), nullable=True),
        sa.Column("noc_contact", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column("admin_contact", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column("comments", sa.String(), nullable=True),
        sa.Column("created_at", src.core.database.types.datetime.DateTimeTZ(timezone=True), nullable=False),
        sa.Column("updated_at", src.core.database.types.datetime.DateTimeTZ(timezone=True), nullable=False),
        sa.Column("created_by_fk", sa.Integer(), nullable=True),
        sa.Column("updated_by_fk", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_isp_created_at"), "isp", ["created_at"], unique=False)
    op.create_index(op.f("ix_isp_id"), "isp", ["id"], unique=False)
    op.create_table(
        "manufacturer",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", postgresql.HSTORE(text_type=sa.Text()), nullable=False),
        sa.Column("slug", sa.String(), nullable=False),
        sa.Column("created_at", src.core.database.types.datetime.DateTimeTZ(timezone=True), nullable=False),
        sa.Column("updated_at", src.core.database.types.datetime.DateTimeTZ(timezone=True), nullable=False),
        sa.Column("created_by_fk", sa.Integer(), nullable=True),
        sa.Column("updated_by_fk", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )
    op.create_index(op.f("ix_manufacturer_created_at"), "manufacturer", ["created_at"], unique=False)
    op.create_index(op.f("ix_manufacturer_id"), "manufacturer", ["id"], unique=False)
    op.create_table(
        "menu",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False, comment="the unique name of route"),
        sa.Column("hidden", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("redirect", sa.String(), nullable=False, comment="redirect url for the route"),
        sa.Column(
            "hideChildrenInMenu",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
            comment="hide children in menu force or not",
        ),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False, comment="the title of the route, 面包屑"),
        sa.Column("icon", sa.String(), nullable=True),
        sa.Column(
            "keepAlive",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
            comment="cache route, 开启multi-tab时为true",
        ),
        sa.Column(
            "hiddenHeaderContent",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
            comment="隐藏pageheader页面带的面包屑和标题栏",
        ),
        sa.Column("permission", postgresql.ARRAY(sa.Integer(), dimensions=1), nullable=True),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["parent_id"], ["menu.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "permission",
        sa.Column("id", src.core.database.types.guid.GUID(length=16), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("url", sa.String(), nullable=False),
        sa.Column("method", sa.String(), nullable=False),
        sa.Column("tag", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_permission_id"), "permission", ["id"], unique=False)
    op.create_table(
        "platform",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("slug", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("netmiko_driver", sa.String(), nullable=True),
        sa.Column("created_at", src.core.database.types.datetime.DateTimeTZ(timezone=True), nullable=False),
        sa.Column("updated_at", src.core.database.types.datetime.DateTimeTZ(timezone=True), nullable=False),
        sa.Column("created_by_fk", sa.Integer(), nullable=True),
        sa.Column("updated_by_fk", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
        sa.UniqueConstraint("slug"),
    )
    op.create_index(op.f("ix_platform_created_at"), "platform", ["created_at"], unique=False)
    op.create_index(op.f("ix_platform_id"), "platform", ["id"], unique=False)
    op.create_table(
        "role",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("slug", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("created_at", src.core.database.types.datetime.DateTimeTZ(timezone=True), nullable=False),
        sa.Column("updated_at", src.core.database.types.datetime.DateTimeTZ(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_role_created_at"), "role", ["created_at"], unique=False)
    op.create_index(op.f("ix_role_id"), "role", ["id"], unique=False)
    op.create_table(
        "route_target",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("created_at", src.core.database.types.datetime.DateTimeTZ(timezone=True), nullable=False),
        sa.Column("updated_at", src.core.database.types.datetime.DateTimeTZ(timezone=True), nullable=False),
        sa.Column("created_by_fk", sa.Integer(), nullable=True),
        sa.Column("updated_by_fk", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(op.f("ix_route_target_created_at"), "route_target", ["created_at"], unique=False)
    op.create_index(op.f("ix_route_target_id"), "route_target", ["id"], unique=False)
    op.create_table(
        "site_group",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("created_at", src.core.database.types.datetime.DateTimeTZ(timezone=True), nullable=False),
        sa.Column("updated_at", src.core.database.types.datetime.DateTimeTZ(timezone=True), nullable=False),
        sa.Column("created_by_fk", sa.Integer(), nullable=True),
        sa.Column("updated_by_fk", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(op.f("ix_site_group_created_at"), "site_group", ["created_at"], unique=False)
    op.create_table(
        "subscription",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("enable", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("enable_time_range", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("time_range", postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.Column("group_delay", sa.Integer(), nullable=False),
        sa.Column("send_repeat", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("repeat_interval", sa.Integer(), nullable=False),
        sa.Column("max_repeat", sa.Integer(), nullable=False),
        sa.Column("send_resolved", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("channel_type", sa.String(), nullable=False),
        sa.Column("channel_config", postgresql.JSON(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", src.core.database.types.datetime.DateTimeTZ(timezone=True), nullable=False),
        sa.Column("updated_at", src.core.database.types.datetime.DateTimeTZ(timezone=True), nullable=False),
        sa.Column("created_by_fk", sa.Integer(), nullable=True),
        sa.Column("updated_by_fk", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_subscription_created_at"), "subscription", ["created_at"], unique=False)
    op.create_index(op.f("ix_subscription_id"), "subscription", ["id"], unique=False)
    op.create_table(
        "template",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("template_id", sa.Integer(), nullable=False),
        sa.Column("discovery_ospf_id", sa.Integer(), nullable=True),
        sa.Column("discovery_bgp_id", sa.Integer(), nullable=True),
        sa.Column("created_at", src.core.database.types.datetime.DateTimeTZ(timezone=True), nullable=False),
        sa.Column("updated_at", src.core.database.types.datetime.DateTimeTZ(timezone=True), nullable=False),
        sa.Column("created_by_fk", sa.Integer(), nullable=True),
        sa.Column("updated_by_fk", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_template_created_at"), "template", ["created_at"], unique=False)
    op.create_index(op.f("ix_template_id"), "template", ["id"], unique=False)
    op.create_table(
        "vrf",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("rd", sa.String(), nullable=False),
        sa.Column(
            "enforce_unique",
            sa.Boolean(),
            server_default=sa.text("true"),
            nullable=False,
            comment="Enforce unique space, prevent duplicate IP/prefix",
        ),
        sa.Column("created_at", src.core.database.types.datetime.DateTimeTZ(timezone=True), nullable=False),
        sa.Column("updated_at", src.core.database.types.datetime.DateTimeTZ(timezone=True), nullable=False),
        sa.Column("created_by_fk", sa.Integer(), nullable=True),
        sa.Column("updated_by_fk", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
        sa.UniqueConstraint("rd"),
    )
    op.create_index(op.f("ix_vrf_created_at"), "vrf", ["created_at"], unique=False)
    op.create_index(op.f("ix_vrf_id"), "vrf", ["id"], unique=False)
    op.create_table(
        "device_type",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("snmp_sysobjectid", sa.String(), nullable=False),
        sa.Column("u_height", sa.Float(), server_default="1.0", nullable=False),
        sa.Column("front_image", sa.String(), nullable=True),
        sa.Column("rear_image", sa.String(), nullable=True),
        sa.Column("manufacturer_id", sa.Integer(), nullable=False),
        sa.Column("platform_id", sa.Integer(), nullable=False),
        sa.Column("created_at", src.core.database.types.datetime.DateTimeTZ(timezone=True), nullable=False),
        sa.Column("updated_at", src.core.database.types.datetime.DateTimeTZ(timezone=True), nullable=False),
        sa.Column("created_by_fk", sa.Integer(), nullable=True),
        sa.Column("updated_by_fk", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["manufacturer_id"], ["manufacturer.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["platform_id"], ["platform.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("manufacturer_id", "name"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(op.f("ix_device_type_created_at"), "device_type", ["created_at"], unique=False)
    op.create_index(op.f("ix_device_type_id"), "device_type", ["id"], unique=False)
    op.create_table(
        "group",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("role_id", sa.Integer(), nullable=False),
        sa.Column("created_at", src.core.database.types.datetime.DateTimeTZ(timezone=True), nullable=False),
        sa.Column("updated_at", src.core.database.types.datetime.DateTimeTZ(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["role_id"], ["role.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_group_created_at"), "group", ["created_at"], unique=False)
    op.create_index(op.f("ix_group_id"), "group", ["id"], unique=False)
    op.create_table(
        "ip_range",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("start_address", src.core.database.types.ipaddress.PgIpInterface(), nullable=False),
        sa.Column("end_address", src.core.database.types.ipaddress.PgIpInterface(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("vrf_id", sa.Integer(), nullable=True),
        sa.Column("created_at", src.core.database.types.datetime.DateTimeTZ(timezone=True), nullable=False),
        sa.Column("updated_at", src.core.database.types.datetime.DateTimeTZ(timezone=True), nullable=False),
        sa.Column("created_by_fk", sa.Integer(), nullable=True),
        sa.Column("updated_by_fk", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["vrf_id"], ["vrf.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_ip_range_created_at"), "ip_range", ["created_at"], unique=False)
    op.create_index(op.f("ix_ip_range_id"), "ip_range", ["id"], unique=False)
    op.create_table(
        "isp_asn",
        sa.Column("isp_id", sa.Integer(), nullable=False),
        sa.Column("asn_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["asn_id"], ["asn.id"]),
        sa.ForeignKeyConstraint(["isp_id"], ["isp.id"]),
        sa.PrimaryKeyConstraint("isp_id", "asn_id"),
    )
    op.create_table(
        "jinja_template",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("template", sa.String(), nullable=False),
        sa.Column("platform_id", sa.Integer(), nullable=False),
        sa.Column("created_at", src.core.database.types.datetime.DateTimeTZ(timezone=True), nullable=False),
        sa.Column("updated_at", src.core.database.types.datetime.DateTimeTZ(timezone=True), nullable=False),
        sa.Column("created_by_fk", sa.Integer(), nullable=True),
        sa.Column("updated_by_fk", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["platform_id"], ["platform.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_jinja_template_created_at"), "jinja_template", ["created_at"], unique=False)
    op.create_index(op.f("ix_jinja_template_id"), "jinja_template", ["id"], unique=False)
    op.create_table(
        "role_menu",
        sa.Column("role_id", sa.Integer(), nullable=False),
        sa.Column("menu_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["menu_id"], ["menu.id"]),
        sa.ForeignKeyConstraint(["role_id"], ["role.id"]),
        sa.PrimaryKeyConstraint("role_id", "menu_id"),
    )
    op.create_table(
        "role_permission",
        sa.Column("role_id", sa.Integer(), nullable=False),
        sa.Column("permission_id", src.core.database.types.guid.GUID(length=16), nullable=False),
        sa.ForeignKeyConstraint(["permission_id"], ["permission.id"]),
        sa.ForeignKeyConstraint(["role_id"], ["role.id"]),
        sa.PrimaryKeyConstraint("role_id", "permission_id"),
    )
    op.create_table(
        "textfsm_template",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("template", sa.String(), nullable=False),
        sa.Column("platform_id", sa.Integer(), nullable=False),
        sa.Column("created_at", src.core.database.types.datetime.DateTimeTZ(timezone=True), nullable=False),
        sa.Column("updated_at", src.core.database.types.datetime.DateTimeTZ(timezone=True), nullable=False),
        sa.Column("created_by_fk", sa.Integer(), nullable=True),
        sa.Column("updated_by_fk", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["platform_id"], ["platform.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_textfsm_template_created_at"), "textfsm_template", ["created_at"], unique=False)
    op.create_index(op.f("ix_textfsm_template_id"), "textfsm_template", ["id"], unique=False)
    op.create_table(
        "vrf_route_target",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("vrf_id", sa.Integer(), nullable=False),
        sa.Column("route_target_id", sa.Integer(), nullable=False),
        sa.Column("target", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(["route_target_id"], ["route_target.id"]),
        sa.ForeignKeyConstraint(["vrf_id"], ["vrf.id"]),
        sa.PrimaryKeyConstraint("id", "vrf_id", "route_target_id"),
    )
    op.create_index(op.f("ix_vrf_route_target_id"), "vrf_route_target", ["id"], unique=False)
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("phone", sa.String(), nullable=True),
        sa.Column("password", sa.String(), nullable=False),
        sa.Column("avatar", sa.String(), nullable=True),
        sa.Column("last_login", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("group_id", sa.Integer(), nullable=False),
        sa.Column("role_id", sa.Integer(), nullable=False),
        sa.Column("auth_info", postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", src.core.database.types.datetime.DateTimeTZ(timezone=True), nullable=False),
        sa.Column("updated_at", src.core.database.types.datetime.DateTimeTZ(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["group_id"], ["group.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["role_id"], ["role.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("phone"),
    )
    op.create_index(op.f("ix_user_created_at"), "user", ["created_at"], unique=False)
    op.create_index(op.f("ix_user_id"), "user", ["id"], unique=False)
    op.create_table(
        "alert_user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("online_date", postgresql.JSON(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", src.core.database.types.datetime.DateTimeTZ(timezone=True), nullable=False),
        sa.Column("updated_at", src.core.database.types.datetime.DateTimeTZ(timezone=True), nullable=False),
        sa.Column("created_by_fk", sa.Integer(), nullable=True),
        sa.Column("updated_by_fk", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_alert_user_created_at"), "alert_user", ["created_at"], unique=False)
    op.create_index(op.f("ix_alert_user_id"), "alert_user", ["id"], unique=False)
    op.create_table(
        "asn_audit_log",
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", src.core.database.types.datetime.DateTimeTZ(timezone=True), nullable=False),
        sa.Column("request_id", sa.String(), nullable=False),
        sa.Column("action", sa.String(), nullable=False),
        sa.Column("diff", sa.JSON(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["parent_id"], ["asn.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_asn_audit_log_id"), "asn_audit_log", ["id"], unique=False)
    op.create_table(
        "block_audit_log",
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", src.core.database.types.datetime.DateTimeTZ(timezone=True), nullable=False),
        sa.Column("request_id", sa.String(), nullable=False),
        sa.Column("action", sa.String(), nullable=False),
        sa.Column("diff", sa.JSON(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["parent_id"], ["block.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_block_audit_log_id"), "block_audit_log", ["id"], unique=False)
    op.create_table(
        "ip_range_audit_log",
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", src.core.database.types.datetime.DateTimeTZ(timezone=True), nullable=False),
        sa.Column("request_id", sa.String(), nullable=False),
        sa.Column("action", sa.String(), nullable=False),
        sa.Column("diff", sa.JSON(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["parent_id"], ["ip_range.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_ip_range_audit_log_id"), "ip_range_audit_log", ["id"], unique=False)
    op.create_table(
        "isp_audit_log",
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", src.core.database.types.datetime.DateTimeTZ(timezone=True), nullable=False),
        sa.Column("request_id", sa.String(), nullable=False),
        sa.Column("action", sa.String(), nullable=False),
        sa.Column("diff", sa.JSON(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["parent_id"], ["isp.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_isp_audit_log_id"), "isp_audit_log", ["id"], unique=False)
    op.create_table(
        "route_target_audit_log",
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", src.core.database.types.datetime.DateTimeTZ(timezone=True), nullable=False),
        sa.Column("request_id", sa.String(), nullable=False),
        sa.Column("action", sa.String(), nullable=False),
        sa.Column("diff", sa.JSON(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["parent_id"], ["route_target.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_route_target_audit_log_id"), "route_target_audit_log", ["id"], unique=False)
    op.create_table(
        "site",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("site_code", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("facility_code", sa.String(), nullable=True),
        sa.Column("time_zone", sa.Integer(), nullable=True),
        sa.Column("country", sa.String(), nullable=True),
        sa.Column("city", sa.String(), nullable=True),
        sa.Column("address", sa.String(), nullable=False),
        sa.Column("latitude", sa.Float(), nullable=False),
        sa.Column("longitude", sa.Float(), nullable=False),
        sa.Column("classification", sa.String(), nullable=True),
        sa.Column("comments", sa.String(), nullable=True),
        sa.Column("site_group_id", sa.Integer(), nullable=True),
        sa.Column("network_contact_id", sa.Integer(), nullable=True),
        sa.Column("it_contact_id", sa.Integer(), nullable=True),
        sa.Column("created_at", src.core.database.types.datetime.DateTimeTZ(timezone=True), nullable=False),
        sa.Column("updated_at", src.core.database.types.datetime.DateTimeTZ(timezone=True), nullable=False),
        sa.Column("created_by_fk", sa.Integer(), nullable=True),
        sa.Column("updated_by_fk", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["it_contact_id"], ["user.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["network_contact_id"], ["user.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["site_group_id"], ["site_group.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(op.f("ix_site_created_at"), "site", ["created_at"], unique=False)
    op.create_index(op.f("ix_site_id"), "site", ["id"], unique=False)
    op.create_index(op.f("ix_site_site_code"), "site", ["site_code"], unique=True)
    op.create_table(
        "vrf_audit_log",
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", src.core.database.types.datetime.DateTimeTZ(timezone=True), nullable=False),
        sa.Column("request_id", sa.String(), nullable=False),
        sa.Column("action", sa.String(), nullable=False),
        sa.Column("diff", sa.JSON(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["parent_id"], ["vrf.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_vrf_audit_log_id"), "vrf_audit_log", ["id"], unique=False)
    op.create_table(
        "event_group",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("group_key", sa.String(), nullable=True),
        sa.Column("content_hash", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("started_at", src.core.database.types.datetime.DateTimeTZ(timezone=True), nullable=False),
        sa.Column("resolved_at", src.core.database.types.datetime.DateTimeTZ(timezone=True), nullable=True),
        sa.Column("acknowledged_at", src.core.database.types.datetime.DateTimeTZ(timezone=True), nullable=True),
        sa.Column("acknowledged_by", sa.Integer(), nullable=True),
        sa.Column("closed_at", src.core.database.types.datetime.DateTimeTZ(timezone=True), nullable=True),
        sa.Column("closed_by", sa.Integer(), nullable=True),
        sa.Column("severity", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(["acknowledged_by"], ["alert_user.id"]),
        sa.ForeignKeyConstraint(["closed_by"], ["alert_user.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_event_group_id"), "event_group", ["id"], unique=False)
    op.create_table(
        "event_operation",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("operation_type", sa.String(), nullable=False),
        sa.Column("comment", sa.String(), nullable=True),
        sa.Column("inhibitor_id", sa.Integer(), nullable=True),
        sa.Column("assignee_id", sa.Integer(), nullable=True),
        sa.Column("created_at", src.core.database.types.datetime.DateTimeTZ(timezone=True), nullable=False),
        sa.Column("created_by", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["assignee_id"], ["alert_user.id"]),
        sa.ForeignKeyConstraint(["created_by"], ["user.id"]),
        sa.ForeignKeyConstraint(["inhibitor_id"], ["inhibitor.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_event_operation_id"), "event_operation", ["id"], unique=False)
    op.create_table(
        "location",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("location_type", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("site_id", sa.Integer(), nullable=False),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("created_at", src.core.database.types.datetime.DateTimeTZ(timezone=True), nullable=False),
        sa.Column("updated_at", src.core.database.types.datetime.DateTimeTZ(timezone=True), nullable=False),
        sa.Column("created_by_fk", sa.Integer(), nullable=True),
        sa.Column("updated_by_fk", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["parent_id"], ["location.id"]),
        sa.ForeignKeyConstraint(["site_id"], ["site.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("site_id", "name"),
    )
    op.create_index(op.f("ix_location_created_at"), "location", ["created_at"], unique=False)
    op.create_table(
        "site_asn",
        sa.Column("site_id", sa.Integer(), nullable=False),
        sa.Column("asn_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["asn_id"], ["asn.id"]),
        sa.ForeignKeyConstraint(["site_id"], ["site.id"]),
        sa.PrimaryKeyConstraint("site_id", "asn_id"),
    )
    op.create_table(
        "site_audit_log",
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", src.core.database.types.datetime.DateTimeTZ(timezone=True), nullable=False),
        sa.Column("request_id", sa.String(), nullable=False),
        sa.Column("action", sa.String(), nullable=False),
        sa.Column("diff", sa.JSON(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["parent_id"], ["site.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_site_audit_log_id"), "site_audit_log", ["id"], unique=False)
    op.create_table(
        "vlan",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("vid", sa.Integer(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("ip_address", sa.String(), nullable=False),
        sa.Column("associated_interfaces", postgresql.ARRAY(sa.String(), dimensions=1), nullable=True),
        sa.Column("site_id", sa.Integer(), nullable=False),
        sa.Column("role_id", sa.Integer(), nullable=True),
        sa.Column("created_at", src.core.database.types.datetime.DateTimeTZ(timezone=True), nullable=False),
        sa.Column("updated_at", src.core.database.types.datetime.DateTimeTZ(timezone=True), nullable=False),
        sa.Column("created_by_fk", sa.Integer(), nullable=True),
        sa.Column("updated_by_fk", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["role_id"], ["ip_role.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["site_id"], ["site.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("site_id", "vid"),
    )
    op.create_index(op.f("ix_vlan_created_at"), "vlan", ["created_at"], unique=False)
    op.create_index(op.f("ix_vlan_id"), "vlan", ["id"], unique=False)
    op.create_table(
        "device",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("management_ip", src.core.database.types.ipaddress.PgIpAddress(), nullable=False),
        sa.Column("oob_ip", src.core.database.types.ipaddress.PgIpAddress(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("software_version", sa.String(), nullable=True),
        sa.Column("software_patch", sa.String(), nullable=True),
        sa.Column("comments", sa.String(), nullable=True),
        sa.Column("serial_number", sa.String(), nullable=True),
        sa.Column("asset_tag", sa.String(), nullable=True),
        sa.Column("device_type_id", sa.Integer(), nullable=False),
        sa.Column("device_role_id", sa.Integer(), nullable=False),
        sa.Column("platform_id", sa.Integer(), nullable=False, comment="redundant platform.id for query performance"),
        sa.Column(
            "manufacturer_id", sa.Integer(), nullable=False, comment="redundant manufacturer.id for query performance"
        ),
        sa.Column("site_id", sa.Integer(), nullable=False),
        sa.Column("location_id", sa.Integer(), nullable=True),
        sa.Column("associated_wac_ip", src.core.database.types.ipaddress.PgIpAddress(), nullable=True),
        sa.Column("ap_group", sa.String(), nullable=True),
        sa.Column("ap_mode", sa.String(), nullable=True),
        sa.Column("created_at", src.core.database.types.datetime.DateTimeTZ(timezone=True), nullable=False),
        sa.Column("updated_at", src.core.database.types.datetime.DateTimeTZ(timezone=True), nullable=False),
        sa.Column("created_by_fk", sa.Integer(), nullable=True),
        sa.Column("updated_by_fk", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["device_role_id"], ["device_role.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["device_type_id"], ["device_type.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["location_id"], ["location.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["manufacturer_id"], ["manufacturer.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["platform_id"], ["platform.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["site_id"], ["site.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("serial_number"),
    )
    op.create_index(op.f("ix_device_created_at"), "device", ["created_at"], unique=False)
    op.create_index(op.f("ix_device_id"), "device", ["id"], unique=False)
    op.create_index(op.f("ix_device_management_ip"), "device", ["management_ip"], unique=False)
    op.create_index(op.f("ix_device_name"), "device", ["name"], unique=False)
    op.create_table(
        "event_operation_event_group",
        sa.Column("event_group_id", sa.Integer(), nullable=False),
        sa.Column("operation_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["event_group_id"], ["event_group.id"]),
        sa.ForeignKeyConstraint(["operation_id"], ["event_operation.id"]),
        sa.PrimaryKeyConstraint("event_group_id", "operation_id"),
    )
    op.create_table(
        "location_audit_log",
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", src.core.database.types.datetime.DateTimeTZ(timezone=True), nullable=False),
        sa.Column("request_id", sa.String(), nullable=False),
        sa.Column("action", sa.String(), nullable=False),
        sa.Column("diff", sa.JSON(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["parent_id"], ["location.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_location_audit_log_id"), "location_audit_log", ["id"], unique=False)
    op.create_table(
        "prefix",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("prefix", src.core.database.types.ipaddress.PgCIDR(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("is_dhcp_pool", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("is_full", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("vlan_id", sa.Integer(), nullable=True),
        sa.Column("site_id", sa.Integer(), nullable=True),
        sa.Column("role_id", sa.Integer(), nullable=True),
        sa.Column("vrf_id", sa.Integer(), nullable=True),
        sa.Column("created_at", src.core.database.types.datetime.DateTimeTZ(timezone=True), nullable=False),
        sa.Column("updated_at", src.core.database.types.datetime.DateTimeTZ(timezone=True), nullable=False),
        sa.Column("created_by_fk", sa.Integer(), nullable=True),
        sa.Column("updated_by_fk", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["role_id"], ["ip_role.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["site_id"], ["site.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["vlan_id"], ["vlan.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["vrf_id"], ["vrf.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_prefix_created_at"), "prefix", ["created_at"], unique=False)
    op.create_index(op.f("ix_prefix_id"), "prefix", ["id"], unique=False)
    op.create_index(op.f("ix_prefix_prefix"), "prefix", ["prefix"], unique=True)
    op.create_table(
        "vlan_audit_log",
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", src.core.database.types.datetime.DateTimeTZ(timezone=True), nullable=False),
        sa.Column("request_id", sa.String(), nullable=False),
        sa.Column("action", sa.String(), nullable=False),
        sa.Column("diff", sa.JSON(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["parent_id"], ["vlan.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_vlan_audit_log_id"), "vlan_audit_log", ["id"], unique=False)
    op.create_table(
        "auth_credential",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("cli", src.core.database.types.encrypted_string.EncryptedString(), nullable=True),
        sa.Column("snmpv2_community", src.core.database.types.encrypted_string.EncryptedString(), nullable=True),
        sa.Column("snmpv3", src.core.database.types.encrypted_string.EncryptedString(), nullable=True),
        sa.Column("site_group_id", sa.Integer(), nullable=True),
        sa.Column("site_id", sa.Integer(), nullable=True),
        sa.Column("device_id", sa.Integer(), nullable=True),
        sa.Column("created_at", src.core.database.types.datetime.DateTimeTZ(timezone=True), nullable=False),
        sa.Column("updated_at", src.core.database.types.datetime.DateTimeTZ(timezone=True), nullable=False),
        sa.Column("created_by_fk", sa.Integer(), nullable=True),
        sa.Column("updated_by_fk", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["device_id"], ["device.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["site_group_id"], ["site_group.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["site_id"], ["site.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_auth_credential_created_at"), "auth_credential", ["created_at"], unique=False)
    op.create_index(op.f("ix_auth_credential_id"), "auth_credential", ["id"], unique=False)
    op.create_table(
        "baseline_config",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("aaa_server", postgresql.ARRAY(sa.String(), dimensions=1), nullable=True),
        sa.Column("dhcp_server", postgresql.ARRAY(sa.String(), dimensions=1), nullable=True),
        sa.Column("dns_server", postgresql.ARRAY(sa.String(), dimensions=1), nullable=True),
        sa.Column("ntp_server", postgresql.ARRAY(sa.String(), dimensions=1), nullable=True),
        sa.Column("syslog_server", postgresql.ARRAY(sa.String(), dimensions=1), nullable=True),
        sa.Column("netflow_server", postgresql.ARRAY(sa.String(), dimensions=1), nullable=True),
        sa.Column("site_group_id", sa.Integer(), nullable=True),
        sa.Column("site_id", sa.Integer(), nullable=True),
        sa.Column("device_id", sa.Integer(), nullable=True),
        sa.Column("created_at", src.core.database.types.datetime.DateTimeTZ(timezone=True), nullable=False),
        sa.Column("updated_at", src.core.database.types.datetime.DateTimeTZ(timezone=True), nullable=False),
        sa.Column("created_by_fk", sa.Integer(), nullable=True),
        sa.Column("updated_by_fk", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["device_id"], ["device.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["site_group_id"], ["site_group.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["site_id"], ["site.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_baseline_config_created_at"), "baseline_config", ["created_at"], unique=False)
    op.create_index(op.f("ix_baseline_config_id"), "baseline_config", ["id"], unique=False)
    op.create_table(
        "device_audit_log",
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", src.core.database.types.datetime.DateTimeTZ(timezone=True), nullable=False),
        sa.Column("request_id", sa.String(), nullable=False),
        sa.Column("action", sa.String(), nullable=False),
        sa.Column("diff", sa.JSON(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["parent_id"], ["device.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_device_audit_log_id"), "device_audit_log", ["id"], unique=False)
    op.create_table(
        "device_config",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("configuration", sa.TEXT(), nullable=False),
        sa.Column("total_lines", sa.Integer(), server_default="0", nullable=False),
        sa.Column("lines_added", sa.Integer(), server_default="0", nullable=False),
        sa.Column("lines_deleted", sa.Integer(), server_default="0", nullable=False),
        sa.Column("lines_updated", sa.Integer(), server_default="0", nullable=False),
        sa.Column("md5_checksum", sa.String(), nullable=True),
        sa.Column("created_by", sa.String(), nullable=False),
        sa.Column("created_at", src.core.database.types.datetime.DateTimeTZ(timezone=True), nullable=False),
        sa.Column("change_event", postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.Column("device_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["device_id"], ["device.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_device_config_id"), "device_config", ["id"], unique=False)
    op.create_table(
        "equipment",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("eq_type", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("device_type", sa.String(), nullable=True),
        sa.Column("serial_number", sa.String(), nullable=True),
        sa.Column("device_id", sa.Integer(), nullable=False),
        sa.Column("created_at", src.core.database.types.datetime.DateTimeTZ(timezone=True), nullable=False),
        sa.Column("updated_at", src.core.database.types.datetime.DateTimeTZ(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["device_id"], ["device.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_equipment_created_at"), "equipment", ["created_at"], unique=False)
    op.create_index(op.f("ix_equipment_id"), "equipment", ["id"], unique=False)
    op.create_table(
        "interface",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("if_index", sa.Integer(), nullable=True),
        sa.Column("speed", sa.Integer(), nullable=True),
        sa.Column("mode", sa.String(), nullable=False),
        sa.Column("interface_type", sa.String(), nullable=True),
        sa.Column("mtu", sa.Integer(), nullable=True),
        sa.Column("admin_status", sa.String(), nullable=False),
        sa.Column("device_id", sa.Integer(), nullable=False),
        sa.Column("vlan_id", sa.Integer(), nullable=True),
        sa.Column("created_at", src.core.database.types.datetime.DateTimeTZ(timezone=True), nullable=False),
        sa.Column("updated_at", src.core.database.types.datetime.DateTimeTZ(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["device_id"], ["device.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["vlan_id"], ["vlan.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("device_id", "name"),
    )
    op.create_index(op.f("ix_interface_created_at"), "interface", ["created_at"], unique=False)
    op.create_table(
        "module",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("serial_number", sa.String(), nullable=True),
        sa.Column("part_number", sa.String(), nullable=True),
        sa.Column("hardware_version", sa.String(), nullable=True),
        sa.Column("physical_index", sa.Integer(), nullable=True),
        sa.Column("replaceable", sa.Boolean(), nullable=True),
        sa.Column("device_id", sa.Integer(), nullable=False),
        sa.Column("created_at", src.core.database.types.datetime.DateTimeTZ(timezone=True), nullable=False),
        sa.Column("updated_at", src.core.database.types.datetime.DateTimeTZ(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["device_id"], ["device.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("serial_number"),
    )
    op.create_index(op.f("ix_module_created_at"), "module", ["created_at"], unique=False)
    op.create_index(op.f("ix_module_id"), "module", ["id"], unique=False)
    op.create_table(
        "monitor",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("device_id", sa.Integer(), nullable=False),
        sa.Column("template_id", sa.Integer(), nullable=False),
        sa.Column("enable_monitor", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("enable_ospf", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("enable_bgp", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("created_at", src.core.database.types.datetime.DateTimeTZ(timezone=True), nullable=False),
        sa.Column("updated_at", src.core.database.types.datetime.DateTimeTZ(timezone=True), nullable=False),
        sa.Column("created_by_fk", sa.Integer(), nullable=True),
        sa.Column("updated_by_fk", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["device_id"], ["device.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["template_id"], ["template.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_monitor_created_at"), "monitor", ["created_at"], unique=False)
    op.create_index(op.f("ix_monitor_id"), "monitor", ["id"], unique=False)
    op.create_table(
        "prefix_audit_log",
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", src.core.database.types.datetime.DateTimeTZ(timezone=True), nullable=False),
        sa.Column("request_id", sa.String(), nullable=False),
        sa.Column("action", sa.String(), nullable=False),
        sa.Column("diff", sa.JSON(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["parent_id"], ["prefix.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_prefix_audit_log_id"), "prefix_audit_log", ["id"], unique=False)
    op.create_table(
        "stack",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("role", sa.String(), nullable=False),
        sa.Column("mac_address", sa.String(), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=True),
        sa.Column("device_type", sa.String(), nullable=False),
        sa.Column("device_id", sa.Integer(), nullable=False),
        sa.Column("created_at", src.core.database.types.datetime.DateTimeTZ(timezone=True), nullable=False),
        sa.Column("updated_at", src.core.database.types.datetime.DateTimeTZ(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["device_id"], ["device.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_stack_created_at"), "stack", ["created_at"], unique=False)
    op.create_index(op.f("ix_stack_id"), "stack", ["id"], unique=False)
    op.create_table(
        "auth_credential_audit_log",
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", src.core.database.types.datetime.DateTimeTZ(timezone=True), nullable=False),
        sa.Column("request_id", sa.String(), nullable=False),
        sa.Column("action", sa.String(), nullable=False),
        sa.Column("diff", sa.JSON(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["parent_id"], ["auth_credential.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_auth_credential_audit_log_id"), "auth_credential_audit_log", ["id"], unique=False)
    op.create_table(
        "baseline_config_audit_log",
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", src.core.database.types.datetime.DateTimeTZ(timezone=True), nullable=False),
        sa.Column("request_id", sa.String(), nullable=False),
        sa.Column("action", sa.String(), nullable=False),
        sa.Column("diff", sa.JSON(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["parent_id"], ["baseline_config.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_baseline_config_audit_log_id"), "baseline_config_audit_log", ["id"], unique=False)
    op.create_table(
        "circuit",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("cid", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("install_date", sa.Date(), nullable=True),
        sa.Column("purchase_term", sa.String(), nullable=True),
        sa.Column("bandwidth", sa.Integer(), nullable=False, comment="Mbps"),
        sa.Column("comments", sa.String(), nullable=True),
        sa.Column(
            "manufacturer_available_ip",
            postgresql.ARRAY(src.core.database.types.ipaddress.PgIpInterface()),
            nullable=True,
        ),
        sa.Column(
            "manufacturer_available_gateway",
            postgresql.ARRAY(src.core.database.types.ipaddress.PgIpAddress()),
            nullable=True,
        ),
        sa.Column("isp_id", sa.Integer(), nullable=False),
        sa.Column("circuit_type_id", sa.Integer(), nullable=False),
        sa.Column("site_a_id", sa.Integer(), nullable=False),
        sa.Column("device_a_id", sa.Integer(), nullable=False),
        sa.Column("interface_a_id", sa.Integer(), nullable=False),
        sa.Column("site_z_id", sa.Integer(), nullable=True),
        sa.Column("device_z_id", sa.Integer(), nullable=True),
        sa.Column("interface_z_id", sa.Integer(), nullable=True),
        sa.Column("created_at", src.core.database.types.datetime.DateTimeTZ(timezone=True), nullable=False),
        sa.Column("updated_at", src.core.database.types.datetime.DateTimeTZ(timezone=True), nullable=False),
        sa.Column("created_by_fk", sa.Integer(), nullable=True),
        sa.Column("updated_by_fk", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["circuit_type_id"], ["circuit_type.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["device_a_id"], ["device.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["device_z_id"], ["device.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["interface_a_id"], ["interface.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["interface_z_id"], ["interface.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["isp_id"], ["isp.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["site_a_id"], ["site.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["site_z_id"], ["site.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("cid"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(op.f("ix_circuit_created_at"), "circuit", ["created_at"], unique=False)
    op.create_index(op.f("ix_circuit_id"), "circuit", ["id"], unique=False)
    op.create_table(
        "event",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("alert_id", sa.Integer(), nullable=False),
        sa.Column("event_group_id", sa.Integer(), nullable=True),
        sa.Column("site_id", sa.Integer(), nullable=False),
        sa.Column("device_id", sa.Integer(), nullable=False),
        sa.Column("device_role_id", sa.Integer(), nullable=False),
        sa.Column("platform_id", sa.Integer(), nullable=False),
        sa.Column("device_type_id", sa.Integer(), nullable=False),
        sa.Column("interface_id", sa.Integer(), nullable=True),
        sa.Column("inhibitor_id", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("started_at", src.core.database.types.datetime.DateTimeTZ(timezone=True), nullable=False),
        sa.Column("resolved_at", src.core.database.types.datetime.DateTimeTZ(timezone=True), nullable=True),
        sa.Column("acknowledged_at", src.core.database.types.datetime.DateTimeTZ(timezone=True), nullable=True),
        sa.Column("acknowledged_by", sa.Integer(), nullable=True),
        sa.Column("closed_at", src.core.database.types.datetime.DateTimeTZ(timezone=True), nullable=True),
        sa.Column("closed_by", sa.Integer(), nullable=True),
        sa.Column("severity", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(["acknowledged_by"], ["alert_user.id"]),
        sa.ForeignKeyConstraint(["alert_id"], ["alert.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["closed_by"], ["alert_user.id"]),
        sa.ForeignKeyConstraint(["device_id"], ["device.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["event_group_id"], ["event_group.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["inhibitor_id"], ["inhibitor.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["interface_id"], ["interface.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["site_id"], ["site.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_event_id"), "event", ["id"], unique=False)
    op.create_table(
        "ip_address",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("address", src.core.database.types.ipaddress.PgIpInterface(), nullable=False),
        sa.Column("vrf_id", sa.Integer(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("dns_name", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("interface_id", sa.Integer(), nullable=True),
        sa.Column("created_at", src.core.database.types.datetime.DateTimeTZ(timezone=True), nullable=False),
        sa.Column("updated_at", src.core.database.types.datetime.DateTimeTZ(timezone=True), nullable=False),
        sa.Column("created_by_fk", sa.Integer(), nullable=True),
        sa.Column("updated_by_fk", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["interface_id"], ["interface.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["vrf_id"], ["vrf.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_ip_address_created_at"), "ip_address", ["created_at"], unique=False)
    op.create_index(op.f("ix_ip_address_id"), "ip_address", ["id"], unique=False)
    op.create_table(
        "lldp_neighbor",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source_interface_id", sa.Integer(), nullable=False),
        sa.Column("source_device_id", sa.Integer(), nullable=False),
        sa.Column("target_interface_id", sa.Integer(), nullable=False),
        sa.Column("target_device_id", sa.Integer(), nullable=False),
        sa.Column("link_status", sa.String(), nullable=True),
        sa.Column("created_at", src.core.database.types.datetime.DateTimeTZ(timezone=True), nullable=False),
        sa.Column("updated_at", src.core.database.types.datetime.DateTimeTZ(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["source_device_id"], ["device.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["source_interface_id"], ["interface.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["target_device_id"], ["device.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["target_interface_id"], ["interface.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_lldp_neighbor_created_at"), "lldp_neighbor", ["created_at"], unique=False)
    op.create_index(op.f("ix_lldp_neighbor_id"), "lldp_neighbor", ["id"], unique=False)
    op.create_table(
        "circuit_audit_log",
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", src.core.database.types.datetime.DateTimeTZ(timezone=True), nullable=False),
        sa.Column("request_id", sa.String(), nullable=False),
        sa.Column("action", sa.String(), nullable=False),
        sa.Column("diff", sa.JSON(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["parent_id"], ["circuit.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_circuit_audit_log_id"), "circuit_audit_log", ["id"], unique=False)
    op.create_table(
        "event_operation_event",
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column("operation_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["event_id"], ["event.id"]),
        sa.ForeignKeyConstraint(["operation_id"], ["event_operation.id"]),
        sa.PrimaryKeyConstraint("event_id", "operation_id"),
    )
    op.create_table(
        "ip_address_audit_log",
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", src.core.database.types.datetime.DateTimeTZ(timezone=True), nullable=False),
        sa.Column("request_id", sa.String(), nullable=False),
        sa.Column("action", sa.String(), nullable=False),
        sa.Column("diff", sa.JSON(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["parent_id"], ["ip_address.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_ip_address_audit_log_id"), "ip_address_audit_log", ["id"], unique=False)
    op.create_table(
        "ip_address_user",
        sa.Column("ip_address_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["ip_address_id"], ["ip_address.id"]),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"]),
        sa.PrimaryKeyConstraint("ip_address_id", "user_id"),
    )
    op.create_table(
        "notification_record",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("subscription_id", sa.Integer(), nullable=False),
        sa.Column("event_id", sa.Integer(), nullable=True),
        sa.Column("event_group_id", sa.Integer(), nullable=True),
        sa.Column("sent_at", src.core.database.types.datetime.DateTimeTZ(timezone=True), nullable=False),
        sa.Column("result_code", sa.String(), nullable=False),
        sa.Column("result_message", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["event_group_id"], ["event_group.id"]),
        sa.ForeignKeyConstraint(["event_id"], ["event.id"]),
        sa.ForeignKeyConstraint(["subscription_id"], ["subscription.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_notification_record_id"), "notification_record", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_notification_record_id"), table_name="notification_record")
    op.drop_table("notification_record")
    op.drop_table("ip_address_user")
    op.drop_index(op.f("ix_ip_address_audit_log_id"), table_name="ip_address_audit_log")
    op.drop_table("ip_address_audit_log")
    op.drop_table("event_operation_event")
    op.drop_index(op.f("ix_circuit_audit_log_id"), table_name="circuit_audit_log")
    op.drop_table("circuit_audit_log")
    op.drop_index(op.f("ix_lldp_neighbor_id"), table_name="lldp_neighbor")
    op.drop_index(op.f("ix_lldp_neighbor_created_at"), table_name="lldp_neighbor")
    op.drop_table("lldp_neighbor")
    op.drop_index(op.f("ix_ip_address_id"), table_name="ip_address")
    op.drop_index(op.f("ix_ip_address_created_at"), table_name="ip_address")
    op.drop_table("ip_address")
    op.drop_index(op.f("ix_event_id"), table_name="event")
    op.drop_table("event")
    op.drop_index(op.f("ix_circuit_id"), table_name="circuit")
    op.drop_index(op.f("ix_circuit_created_at"), table_name="circuit")
    op.drop_table("circuit")
    op.drop_index(op.f("ix_baseline_config_audit_log_id"), table_name="baseline_config_audit_log")
    op.drop_table("baseline_config_audit_log")
    op.drop_index(op.f("ix_auth_credential_audit_log_id"), table_name="auth_credential_audit_log")
    op.drop_table("auth_credential_audit_log")
    op.drop_index(op.f("ix_stack_id"), table_name="stack")
    op.drop_index(op.f("ix_stack_created_at"), table_name="stack")
    op.drop_table("stack")
    op.drop_index(op.f("ix_prefix_audit_log_id"), table_name="prefix_audit_log")
    op.drop_table("prefix_audit_log")
    op.drop_index(op.f("ix_monitor_id"), table_name="monitor")
    op.drop_index(op.f("ix_monitor_created_at"), table_name="monitor")
    op.drop_table("monitor")
    op.drop_index(op.f("ix_module_id"), table_name="module")
    op.drop_index(op.f("ix_module_created_at"), table_name="module")
    op.drop_table("module")
    op.drop_index(op.f("ix_interface_created_at"), table_name="interface")
    op.drop_table("interface")
    op.drop_index(op.f("ix_equipment_id"), table_name="equipment")
    op.drop_index(op.f("ix_equipment_created_at"), table_name="equipment")
    op.drop_table("equipment")
    op.drop_index(op.f("ix_device_config_id"), table_name="device_config")
    op.drop_table("device_config")
    op.drop_index(op.f("ix_device_audit_log_id"), table_name="device_audit_log")
    op.drop_table("device_audit_log")
    op.drop_index(op.f("ix_baseline_config_id"), table_name="baseline_config")
    op.drop_index(op.f("ix_baseline_config_created_at"), table_name="baseline_config")
    op.drop_table("baseline_config")
    op.drop_index(op.f("ix_auth_credential_id"), table_name="auth_credential")
    op.drop_index(op.f("ix_auth_credential_created_at"), table_name="auth_credential")
    op.drop_table("auth_credential")
    op.drop_index(op.f("ix_vlan_audit_log_id"), table_name="vlan_audit_log")
    op.drop_table("vlan_audit_log")
    op.drop_index(op.f("ix_prefix_prefix"), table_name="prefix")
    op.drop_index(op.f("ix_prefix_id"), table_name="prefix")
    op.drop_index(op.f("ix_prefix_created_at"), table_name="prefix")
    op.drop_table("prefix")
    op.drop_index(op.f("ix_location_audit_log_id"), table_name="location_audit_log")
    op.drop_table("location_audit_log")
    op.drop_table("event_operation_event_group")
    op.drop_index(op.f("ix_device_name"), table_name="device")
    op.drop_index(op.f("ix_device_management_ip"), table_name="device")
    op.drop_index(op.f("ix_device_id"), table_name="device")
    op.drop_index(op.f("ix_device_created_at"), table_name="device")
    op.drop_table("device")
    op.drop_index(op.f("ix_vlan_id"), table_name="vlan")
    op.drop_index(op.f("ix_vlan_created_at"), table_name="vlan")
    op.drop_table("vlan")
    op.drop_index(op.f("ix_site_audit_log_id"), table_name="site_audit_log")
    op.drop_table("site_audit_log")
    op.drop_table("site_asn")
    op.drop_index(op.f("ix_location_created_at"), table_name="location")
    op.drop_table("location")
    op.drop_index(op.f("ix_event_operation_id"), table_name="event_operation")
    op.drop_table("event_operation")
    op.drop_index(op.f("ix_event_group_id"), table_name="event_group")
    op.drop_table("event_group")
    op.drop_index(op.f("ix_vrf_audit_log_id"), table_name="vrf_audit_log")
    op.drop_table("vrf_audit_log")
    op.drop_index(op.f("ix_site_site_code"), table_name="site")
    op.drop_index(op.f("ix_site_id"), table_name="site")
    op.drop_index(op.f("ix_site_created_at"), table_name="site")
    op.drop_table("site")
    op.drop_index(op.f("ix_route_target_audit_log_id"), table_name="route_target_audit_log")
    op.drop_table("route_target_audit_log")
    op.drop_index(op.f("ix_isp_audit_log_id"), table_name="isp_audit_log")
    op.drop_table("isp_audit_log")
    op.drop_index(op.f("ix_ip_range_audit_log_id"), table_name="ip_range_audit_log")
    op.drop_table("ip_range_audit_log")
    op.drop_index(op.f("ix_block_audit_log_id"), table_name="block_audit_log")
    op.drop_table("block_audit_log")
    op.drop_index(op.f("ix_asn_audit_log_id"), table_name="asn_audit_log")
    op.drop_table("asn_audit_log")
    op.drop_index(op.f("ix_alert_user_id"), table_name="alert_user")
    op.drop_index(op.f("ix_alert_user_created_at"), table_name="alert_user")
    op.drop_table("alert_user")
    op.drop_index(op.f("ix_user_id"), table_name="user")
    op.drop_index(op.f("ix_user_created_at"), table_name="user")
    op.drop_table("user")
    op.drop_index(op.f("ix_vrf_route_target_id"), table_name="vrf_route_target")
    op.drop_table("vrf_route_target")
    op.drop_index(op.f("ix_textfsm_template_id"), table_name="textfsm_template")
    op.drop_index(op.f("ix_textfsm_template_created_at"), table_name="textfsm_template")
    op.drop_table("textfsm_template")
    op.drop_table("role_permission")
    op.drop_table("role_menu")
    op.drop_index(op.f("ix_jinja_template_id"), table_name="jinja_template")
    op.drop_index(op.f("ix_jinja_template_created_at"), table_name="jinja_template")
    op.drop_table("jinja_template")
    op.drop_table("isp_asn")
    op.drop_index(op.f("ix_ip_range_id"), table_name="ip_range")
    op.drop_index(op.f("ix_ip_range_created_at"), table_name="ip_range")
    op.drop_table("ip_range")
    op.drop_index(op.f("ix_group_id"), table_name="group")
    op.drop_index(op.f("ix_group_created_at"), table_name="group")
    op.drop_table("group")
    op.drop_index(op.f("ix_device_type_id"), table_name="device_type")
    op.drop_index(op.f("ix_device_type_created_at"), table_name="device_type")
    op.drop_table("device_type")
    op.drop_index(op.f("ix_vrf_id"), table_name="vrf")
    op.drop_index(op.f("ix_vrf_created_at"), table_name="vrf")
    op.drop_table("vrf")
    op.drop_index(op.f("ix_template_id"), table_name="template")
    op.drop_index(op.f("ix_template_created_at"), table_name="template")
    op.drop_table("template")
    op.drop_index(op.f("ix_subscription_id"), table_name="subscription")
    op.drop_index(op.f("ix_subscription_created_at"), table_name="subscription")
    op.drop_table("subscription")
    op.drop_index(op.f("ix_site_group_created_at"), table_name="site_group")
    op.drop_table("site_group")
    op.drop_index(op.f("ix_route_target_id"), table_name="route_target")
    op.drop_index(op.f("ix_route_target_created_at"), table_name="route_target")
    op.drop_table("route_target")
    op.drop_index(op.f("ix_role_id"), table_name="role")
    op.drop_index(op.f("ix_role_created_at"), table_name="role")
    op.drop_table("role")
    op.drop_index(op.f("ix_platform_id"), table_name="platform")
    op.drop_index(op.f("ix_platform_created_at"), table_name="platform")
    op.drop_table("platform")
    op.drop_index(op.f("ix_permission_id"), table_name="permission")
    op.drop_table("permission")
    op.drop_table("menu")
    op.drop_index(op.f("ix_manufacturer_id"), table_name="manufacturer")
    op.drop_index(op.f("ix_manufacturer_created_at"), table_name="manufacturer")
    op.drop_table("manufacturer")
    op.drop_index(op.f("ix_isp_id"), table_name="isp")
    op.drop_index(op.f("ix_isp_created_at"), table_name="isp")
    op.drop_table("isp")
    op.drop_index(op.f("ix_ip_role_id"), table_name="ip_role")
    op.drop_index(op.f("ix_ip_role_created_at"), table_name="ip_role")
    op.drop_table("ip_role")
    op.drop_index(op.f("ix_inhibitor_id"), table_name="inhibitor")
    op.drop_index(op.f("ix_inhibitor_created_at"), table_name="inhibitor")
    op.drop_table("inhibitor")
    op.drop_index(op.f("ix_device_role_id"), table_name="device_role")
    op.drop_index(op.f("ix_device_role_created_at"), table_name="device_role")
    op.drop_table("device_role")
    op.drop_index(op.f("ix_correlation_id"), table_name="correlation")
    op.drop_index(op.f("ix_correlation_created_at"), table_name="correlation")
    op.drop_table("correlation")
    op.drop_index(op.f("ix_circuit_type_id"), table_name="circuit_type")
    op.drop_index(op.f("ix_circuit_type_created_at"), table_name="circuit_type")
    op.drop_table("circuit_type")
    op.drop_index(op.f("ix_block_id"), table_name="block")
    op.drop_index(op.f("ix_block_created_at"), table_name="block")
    op.drop_table("block")
    op.drop_index(op.f("ix_asn_id"), table_name="asn")
    op.drop_index(op.f("ix_asn_created_at"), table_name="asn")
    op.drop_table("asn")
    op.drop_index(op.f("ix_alert_id"), table_name="alert")
    op.drop_index(op.f("ix_alert_created_at"), table_name="alert")
    op.drop_table("alert")
    # ### end Alembic commands ###
